### ISSUE TITLE
Performance issues with BufReadPre hook

### ISSUE THREAD

**Issue by instanceofme** [mantiz/vim-plugin-dirsettings#3]
On my configuration, I found out that the `BufReadPre` hook causes the `PrepareBuffer` function to be called a huge number of time, e.g. when performing `vimgrep /something/ **/*.ext` commands on a project with hundreds of files. Each `:cnext` would take several seconds.

Commenting this hook seemed to resolve the hog.

Which cases are covered by `BufReadPre` and not by the 3 other hooks ?

**Comment by mantiz** [comment]
I will close this issue since it never occurred to me and I have no idea what I can do to solve it.
If anyone finds this issue and has an idea on how to solve it, please feel free to leave a message, or even better, provide a pull request with the solution. :)
