### ISSUE TITLE
test008_tags_loaded fails on OSX

### ISSUE THREAD

**Issue by salomvary** [mantiz/vim-plugin-dirsettings#5]
I assume it actually fails on any case-insensitive file system since `tags` and `TAGS` are the same file.

```
test008_tags_loaded:
FAIL (msgout): The message assertion was not satisfied by the output: 
 --> Message assertion 1 from lines 2-4 did not match in output lines 1-3
     "../data/directory-only/tags/empty" $
     "../data/directory-only/tags/empty" 0L, 0C$
     tags successfull appended$
```

**Comment by mantiz** [comment]
Thanks for the report.

I only have a linux machine which makes it hard to debug for me. :-/

A quick test using a vfat filesystem didn't show the problem, so the problem might be somewhere else.
Maybe the default value of `tags` differs from `./tags,./TAGS,tags,TAGS` and is more like `./tags,tags` or `./TAGS,TAGS` or something similar.

I changed the testscript `test008_tags_loaded.vim` locally to
```
let s:tags_before = &tags

edit ../data/directory-only/tags/empty

if (&tags == s:tags_before . ',' . $HOME . '/directory-only/tags/.vim/tags')
        echo "tags successfull appended"
endif

quit!
```

and it worked for me. It would be great if you could test the above version on your machine.

If it still isn't working, could you please add `echo &tags` right above the condition, run the tests with `TESTDEBUG=1 ./runTests.sh` and paste the content of the file `tests/src/test008_tags_loaded.msgout`?

Would be nice if we can solve this problem. :)

**Comment by salomvary** [comment]
Yup, that did the job, all tests pass with the change above.

**Comment by mantiz** [comment]
Great, thanks.
